name: destroy
on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

env:
  WORKLOAD_WORKING_DIRECTORY: iac/workload
  WORKLOAD_REMOTE_STATE_KEY: dbx.terraform.tfstate
  DBX_RESOURCES_WORKING_DIRECTORY: iac/dbx
  DBX_RESOURCES_REMOTE_STATE_KEY: dbx-resources.terraform.tfstate
  REMOTE_STATE_RG: dbx-demo-eastus2
  REMOTE_STATE_SA: tfdbxed
  REMOTE_STATE_CONTAINER: dbx-remote-state-eastus2-demo
  ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}

permissions:
  id-token: write
  contents: read

jobs:
  destroy-dbx-resources:
    name: 'destroy dbx resources'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.DBX_RESOURCES_WORKING_DIRECTORY }}
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v2
      - name: 'Az CLI Login'
        uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
      - name: 'Get Deployer Secrets'
        id: get-deployer-secret
        uses: azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{ secrets.DEPLOYER_KEY_VAULT }}
          secrets: 'dbx-demo-eastus2-deployer, tfdbxed-access-key'
      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v1
      - name: 'Terraform Init'
        env: 
          TF_CLI_ARGS_init: "-backend-config='resource_group_name=${{env.REMOTE_STATE_RG}}' -backend-config='storage_account_name=${{env.REMOTE_STATE_SA}}' -backend-config='container_name=${{env.REMOTE_STATE_CONTAINER}}' -backend-config='key=${{env.DBX_RESOURCES_REMOTE_STATE_KEY}}'"
          ARM_ACCESS_KEY: ${{ steps.get-deployer-secret.outputs.tfdbxed-access-key }}
        run: terraform init
      - name: 'Terraform Validate'
        run: terraform validate
      - name: 'Terraform Destroy'
        env:        
          ARM_CLIENT_SECRET: ${{ steps.get-deployer-secret.outputs.dbx-demo-eastus2-deployer }}
          TF_VAR_client_secret: ${{ steps.get-deployer-secret.outputs.dbx-demo-eastus2-deployer }}
          ARM_ACCESS_KEY: ${{ steps.get-deployer-secret.outputs.tfdbxed-access-key }}
        run: terraform destroy -auto-approve
  destroy-workload:
    name: 'destroy workload'
    needs: destroy-dbx-resources
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKLOAD_WORKING_DIRECTORY }}
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v2
      - name: 'Az CLI Login'
        uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
      - name: 'Get Deployer Secrets'
        id: get-deployer-secret
        uses: azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{ secrets.DEPLOYER_KEY_VAULT }}
          secrets: 'dbx-demo-eastus2-deployer, tfdbxed-access-key'
      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v1
      - name: 'Terraform Init'
        env: 
          TF_CLI_ARGS_init: "-backend-config='resource_group_name=${{env.REMOTE_STATE_RG}}' -backend-config='storage_account_name=${{env.REMOTE_STATE_SA}}' -backend-config='container_name=${{env.REMOTE_STATE_CONTAINER}}' -backend-config='key=${{env.WORKLOAD_REMOTE_STATE_KEY}}'"
          ARM_ACCESS_KEY: ${{ steps.get-deployer-secret.outputs.tfdbxed-access-key }}
        run: terraform init
      - name: 'Terraform Validate'
        run: terraform validate
      - name: 'Terraform Destroy'
        env:        
          ARM_CLIENT_SECRET: ${{ steps.get-deployer-secret.outputs.dbx-demo-eastus2-deployer }}
          ARM_ACCESS_KEY: ${{ steps.get-deployer-secret.outputs.tfdbxed-access-key }}
          TF_VAR_snowflake_url: ${{ secrets.SNOWFLAKE_URL }}
          TF_VAR_snowflake_username: ${{ secrets.SNOWFLAKE_USERNAME }}
          TF_VAR_snowflake_password: ${{ secrets.SNOWFLAKE_PASSWORD }}
        run: terraform destroy -auto-approve